# Site settings
author: Megann Comstock
title: 
header-img: img/home-bg.png
email: megann.elizabeth.king@gmail.com
copyright_name: Megann Comstock
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: electrila
github_username:  Electrila

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
